#!/usr/bin/env python
# coding: utf-8

# **Tools for retrieving a reference run for a given run**
#
# Preliminary implementation, based on a json file generated by the Tracker DQM group. Retrieved from [here](https://certhelper.web.cern.ch/mldatasets/allRunsRefRuns/) .
# Perhaps modify code later to fetch the up-to-date version at runtime instead of having to download a new version. Maybe also using an API to retrieve only the requested run instead of loading the entire file into memory.


### imports

# external modules
import os

# local modules
# import .json_utils as jsonu
# from .json_utils import loadjson


def get_reference(runnb, jsonlist=None, jsonfile="json_allRunsRefRuns.json"):
    """
    Fetches the reference run used for a given run number

    Args:
        runnb: run number
        jsonlist: list matching run numbers to reference run numbers
        jsonfile: path to json file matching run numbers to reference run number

    Returns:
        Integer representing the reference run that was used in the certification of the given run OR -1 if the given run is not in the json
    """

    if jsonlist is None:
        if not os.path.exists(jsonfile):
            raise Exception(
                "ERROR in refruns_utils.py / get_reference_run: file {} does not exist".format(
                    jsonfile
                )
            )
        jsonlist = loadjson(jsonfile)
        with open(jsonfile) as f:
            jsondict = json.load(f)

    return next(
        (
            item["reference_run_number"]
            for item in jsonlist
            if item["run_number"] == runnb
        ),
        -1,
    )
